# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bbj7uBCQ8ML_W-ynmyaapDRO9R0x5MAC
"""



import pandas as pd

def load_data(path="data/job_market_skills.csv"):
    df = pd.read_csv(path)

    # Standardize column names
    df.columns = df.columns.str.lower().str.strip()

    # Rename columns for consistency
    df = df.rename(columns={
        "job title": "job_title",
        "salary": "salary",
        "location": "location",
        "skills": "skills"
    })

    # Drop rows with missing important values
    df = df.dropna(subset=["job_title", "skills"])

    # Clean salary column (if exists)
    if "salary" in df.columns:
        df["salary"] = (
            df["salary"]
            .astype(str)
            .str.replace(",", "")
            .str.extract(r"(\d+)")
        )
        df["salary"] = pd.to_numeric(df["salary"], errors="coerce")

    return df

"""Once you have the content, you can copy and paste it into a new code cell, or if you prefer an automated way, you can generate a new cell programmatically (though direct generation of arbitrary code cells from string content into the notebook is not a standard Colab API feature for users, printing it is the most direct way for you to then copy/paste or execute dynamically if needed)."""